#!/usr/bin/env bash
# b4_execute.sh — runs the full B4 prep pipeline up to (but NOT including) the
# actual broadcast. Picks a funded P2WPKH UTXO, runs maker-sign, runs envelope
# publish --dry-run, then prints the EXACT --broadcast command for you to
# copy-paste once you've verified the dry-run output.
#
# Why this exists: B4 has three commands (maker-sign, dry-run publish, real
# publish). Doing them by hand means three rounds of copy-paste with UTXO ids,
# artifact hex, etc. flying between them. This script captures the artifact
# automatically and emits the final command pre-filled.
#
# Usage: set the same env vars as for b4_preflight.sh, then run:
#   bash b4_execute.sh
#
# IMPORTANT: in EXTERNAL_RPC mode this script generates a small bitcoin-cli
# wrapper at $HOME/.btx/bcli-external-rpc.sh that injects -rpcconnect/-rpcuser/
# -rpcpassword. The wrapper has chmod 700 so other users can't read your
# password. The Python publisher/wallet scripts only accept --bitcoin-cli +
# --datadir, not direct RPC flags, so the wrapper bridges them transparently.

set -u

# ---- defaults; override via env ----
BTX_BIN=${BTX_BIN:-$HOME/.btx/bin}
BTX_DATADIR=${BTX_DATADIR:-$HOME/.bitcoin}
BTX_WALLET=${BTX_WALLET:-btx}
BTX_REPO=${BTX_REPO:-/mnt/c/Users/Ren Shu/Documents/Claude/Projects/bitcoin-terminal-exchange}
BTX_RPCCONNECT=${BTX_RPCCONNECT:-}
BTX_RPCPORT=${BTX_RPCPORT:-8332}
BTX_RPCUSER=${BTX_RPCUSER:-}
BTX_RPCPASSWORD=${BTX_RPCPASSWORD:-}
BTX_FEE_SATS=${BTX_FEE_SATS:-403}
BTX_COMMIT_BTC=${BTX_COMMIT_BTC:-0.0000546}
BTX_RUNE_BLOCK=${BTX_RUNE_BLOCK:-9999999}
BTX_RUNE_TX=${BTX_RUNE_TX:-1}
BTX_PRICE_BTC=${BTX_PRICE_BTC:-1.0}
BTX_AMOUNT_UNITS=${BTX_AMOUNT_UNITS:-1}
MAX_OFFER_SATS=${MAX_OFFER_SATS:-20000}

note()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()    { printf '\033[32m[OK]\033[0m %s\n' "$*"; }
fail()  { printf '\033[31m[FAIL]\033[0m %s\n' "$*"; }

BCLI_BIN_REAL="$BTX_BIN/bitcoin-cli"

# Generate the bitcoin-cli we'll pass to Python (either real binary or wrapper)
if [ -n "$BTX_RPCCONNECT" ]; then
    WRAPPER="$HOME/.btx/bcli-external-rpc.sh"
    mkdir -p "$HOME/.btx"
    cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# auto-generated by b4_execute.sh — bridges --datadir-style invocation to
# --rpcconnect with the configured RPC credentials. Passwords here are
# sensitive; chmod 700.
exec $BCLI_BIN_REAL \\
    -rpcconnect=$BTX_RPCCONNECT -rpcport=$BTX_RPCPORT \\
    -rpcuser=$BTX_RPCUSER -rpcpassword=$BTX_RPCPASSWORD \\
    "\$@"
EOF
    chmod 700 "$WRAPPER"
    BCLI_FOR_PY="$WRAPPER"
    # Probe BCLI used for our own queries inside this script:
    BCLI_PROBE="$BCLI_BIN_REAL -rpcconnect=$BTX_RPCCONNECT -rpcport=$BTX_RPCPORT -rpcuser=$BTX_RPCUSER -rpcpassword=$BTX_RPCPASSWORD -rpcwallet=$BTX_WALLET"
    MODE="EXTERNAL_RPC ($BTX_RPCCONNECT:$BTX_RPCPORT, wallet=$BTX_WALLET)"
    PY_CONN_FLAGS="--datadir /tmp/btx-fake-datadir"  # ignored by bitcoin-cli when -rpcconnect is set, but Python passes it
else
    BCLI_FOR_PY="$BCLI_BIN_REAL"
    BCLI_PROBE="$BCLI_BIN_REAL -datadir=$BTX_DATADIR -rpcwallet=$BTX_WALLET"
    MODE="datadir ($BTX_DATADIR, wallet=$BTX_WALLET)"
    PY_CONN_FLAGS="--datadir $BTX_DATADIR"
fi

printf '\n==> BTX B4 execute (%s)\n    mode: %s\n    bcli-for-py: %s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$MODE" "$BCLI_FOR_PY"

# ---- A. Run preflight first ----
note "running b4_preflight.sh"
cd "$BTX_REPO"
if ! bash b4_preflight.sh > /tmp/b4-preflight.log 2>&1; then
    fail "preflight RED — see /tmp/b4-preflight.log"
    tail -25 /tmp/b4-preflight.log
    exit 1
fi
ok "preflight passed"
grep -E '^\[(OK|WARN)\]|GREEN|YELLOW' /tmp/b4-preflight.log | tail -10

# ---- B. Pick the funded P2WPKH UTXO ----
note "picking offer UTXO"
PICKED=$($BCLI_PROBE listunspent 1 9999999 2>&1 | python3 -c "
import sys, json
d = json.load(sys.stdin)
target_max = $MAX_OFFER_SATS / 100000000
best = None
for u in d:
    if u['scriptPubKey'].startswith('0014') and u['amount'] >= 0.00005 and u['amount'] <= target_max * 2:
        if best is None or u['amount'] < best['amount']:
            best = u
print(json.dumps(best) if best else '')
")
if [ -z "$PICKED" ]; then
    fail "no suitable P2WPKH UTXO (need >= 5000 sats, prefer <= $MAX_OFFER_SATS sats)"
    exit 1
fi
OFFER_TXID=$(echo "$PICKED" | python3 -c 'import sys,json;print(json.load(sys.stdin)["txid"])')
OFFER_VOUT=$(echo "$PICKED" | python3 -c 'import sys,json;print(json.load(sys.stdin)["vout"])')
OFFER_AMT_BTC=$(echo "$PICKED" | python3 -c 'import sys,json;print(json.load(sys.stdin)["amount"])')
OFFER_AMT_SATS=$(python3 -c "print(int(round($OFFER_AMT_BTC * 100000000)))")
ok "offer UTXO: $OFFER_TXID:$OFFER_VOUT = $OFFER_AMT_BTC BTC ($OFFER_AMT_SATS sats)"

# ---- C. Maker-sign ----
note "running maker-sign (locks the offer UTXO, produces artifact_hex)"
MS_OUT=$(python3 btx_wallet.py maker-sign \
    --bitcoin-cli "$BCLI_FOR_PY" \
    --chain main \
    $PY_CONN_FLAGS \
    --wallet "$BTX_WALLET" \
    --offer-txid "$OFFER_TXID" --offer-vout "$OFFER_VOUT" \
    --price-btc "$BTX_PRICE_BTC" \
    --amount-units "$BTX_AMOUNT_UNITS" \
    --rune-block "$BTX_RUNE_BLOCK" --rune-tx "$BTX_RUNE_TX" \
    --carrier envelope 2>&1)
RC=$?
if [ $RC -ne 0 ]; then
    fail "maker-sign failed:"
    echo "$MS_OUT" | head -15
    exit 1
fi
ARTIFACT_HEX=$(echo "$MS_OUT" | python3 -c "
import sys, json
out = sys.stdin.read()
i = out.find('{')
j = out.rfind('}')
d = json.loads(out[i:j+1])
print(d.get('artifact_hex',''))
" 2>&1)
ARTIFACT_BYTES=$(echo "$MS_OUT" | python3 -c "
import sys, json
out = sys.stdin.read()
i = out.find('{')
j = out.rfind('}')
d = json.loads(out[i:j+1])
print(d.get('artifact_bytes','?'))
" 2>&1)
if [ -z "$ARTIFACT_HEX" ] || [ "${ARTIFACT_HEX:0:8}" != "42545831" ]; then
    fail "artifact_hex missing or wrong magic. Full maker-sign output:"
    echo "$MS_OUT"
    exit 1
fi
ok "artifact: $ARTIFACT_BYTES bytes, magic BTX1, hex=${ARTIFACT_HEX:0:32}..."

# ---- D. Dry-run publish ----
note "running envelope publish --dry-run (no broadcast yet)"
STATE_FILE="$HOME/.btx/b4-state-$(date +%s).json"
DRY_OUT=$(python3 btx_envelope_publish.py publish \
    --artifact-hex "$ARTIFACT_HEX" \
    --bitcoin-cli "$BCLI_FOR_PY" \
    --chain main \
    $PY_CONN_FLAGS \
    --wallet "$BTX_WALLET" \
    --commit-amount-btc "$BTX_COMMIT_BTC" \
    --fee-sats "$BTX_FEE_SATS" \
    --dry-run 2>&1)
RC=$?
if [ $RC -ne 0 ]; then
    fail "dry-run failed:"
    echo "$DRY_OUT" | head -15
    $BCLI_PROBE lockunspent true "[{\"txid\":\"$OFFER_TXID\",\"vout\":$OFFER_VOUT}]" 2>&1
    exit 1
fi
COMMIT_ADDR=$(echo "$DRY_OUT" | python3 -c "
import sys, json
out = sys.stdin.read()
i = out.find('{')
j = out.rfind('}')
d = json.loads(out[i:j+1])
print(d.get('commit_address',''))
" 2>&1)
if [ -z "$COMMIT_ADDR" ] || [ "${COMMIT_ADDR:0:4}" != "bc1p" ]; then
    fail "commit address wrong (expected bc1p...): $COMMIT_ADDR"
    $BCLI_PROBE lockunspent true "[{\"txid\":\"$OFFER_TXID\",\"vout\":$OFFER_VOUT}]" 2>&1
    exit 1
fi
ok "dry-run OK; commit address: $COMMIT_ADDR (mainnet P2TR, prefix bc1p ✓)"

# ---- E. Print the EXACT broadcast command ----
note "BROADCAST COMMAND (verify everything below, then copy-paste to execute B4)"
echo
echo "  # State file (recovery if anything fails): $STATE_FILE"
echo "  # Reveal fee: $BTX_FEE_SATS sats. Commit amount: $BTX_COMMIT_BTC BTC ($(python3 -c "print(int(round($BTX_COMMIT_BTC * 100000000)))") sats)"
echo "  # Offer UTXO locked: $OFFER_TXID:$OFFER_VOUT ($OFFER_AMT_SATS sats — at absurd price, no one can fill)"
echo "  # Commit P2TR: $COMMIT_ADDR"
echo
echo "  # =================================================================="
echo "  # COPY-PASTE THIS BLOCK TO BROADCAST (one ENTER to execute)"
echo "  # =================================================================="
cat <<EOF

cd "$BTX_REPO"

python3 btx_envelope_publish.py publish \\
    --artifact-hex "$ARTIFACT_HEX" \\
    --bitcoin-cli "$BCLI_FOR_PY" \\
    --chain main \\
    $PY_CONN_FLAGS \\
    --wallet $BTX_WALLET \\
    --commit-amount-btc $BTX_COMMIT_BTC \\
    --fee-sats $BTX_FEE_SATS \\
    --state-file "$STATE_FILE" \\
    --broadcast

EOF
echo "  # =================================================================="
echo
note "what to do next"
echo "  1. Review the broadcast block above. Confirm everything looks right."
echo "  2. Copy + paste into your terminal. Output contains commit_txid + reveal_txid."
echo "  3. After broadcast: follow BTX-post-B4-playbook.md to verify + record."
echo
echo "  Want to ABORT instead? Release the lock with:"
echo "    $BCLI_PROBE lockunspent true '[{\"txid\":\"$OFFER_TXID\",\"vout\":$OFFER_VOUT}]'"
